python learn_exec.py $1 null
python learn_exec.py $1 c
python learn_exec.py $1 a
python learn_exec.py $1 t
python learn_exec.py $1 ca
python learn_exec.py $1 ct
python learn_exec.py $1 at
python learn_exec.py $1 cat
python learn_exec.py $1 enum
